import { useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "@/components/ui/DashboardLayout";
import { 
  Shield, 
  Lock, 
  Key, 
  Smartphone, 
  Mail, 
  Eye, 
  Users, 
  Clock,
  AlertTriangle,
  CheckCircle,
  Zap,
  Headphones,
  Ticket,
  ArrowLeft,
  Fingerprint
} from "lucide-react";

const AccountSecurityPage = () => {
  const navigate = useNavigate();
  const [activeSection, setActiveSection] = useState("two-factor");

  const guides = [
    {
      id: "two-factor",
      title: "Two-Factor Authentication (2FA)",
      description: "Add an extra layer of security to your account",
      icon: Fingerprint,
      color: "blue",
      steps: [
        { title: "What is 2FA?", desc: "Two-Factor Authentication adds an extra security layer by requiring not just your password, but also a second verification method (a code sent to your phone or generated by an app) to access your account." },
        { title: "Enable 2FA", desc: "Go to Settings > Security > Two-Factor Authentication. Click 'Enable' to start the setup process. You'll need either a mobile authenticator app (Google Authenticator, Authy) or SMS verification." },
        { title: "Authenticator App Setup", desc: "Download Google Authenticator or Authy from your app store. Scan the QR code displayed on your screen with the app. Enter the 6-digit code shown in the app to verify setup." },
        { title: "SMS Verification Setup", desc: "If you prefer SMS, enter your phone number. We'll send a verification code each time you log in. This is less secure than authenticator apps but more convenient." },
        { title: "Backup Codes", desc: "After enabling 2FA, you'll receive 10 backup codes. Save these in a secure location - they're your fallback if you lose access to your authenticator app or phone." },
        { title: "Recovery Options", desc: "If you're locked out, use a backup code or contact our support team with identity verification to regain access. We can help you reset 2FA after proper verification." }
      ]
    },
    {
      id: "password",
      title: "Password Management",
      description: "Create and maintain strong passwords",
      icon: Lock,
      color: "green",
      steps: [
        { title: "Creating Strong Passwords", desc: "Use at least 12 characters with a mix of uppercase, lowercase, numbers, and symbols. Avoid personal information like birthdays or names. Use a password manager for generating and storing unique passwords." },
        { title: "Password Requirements", desc: "Your SOLEASE password must be at least 8 characters. We recommend 16+ characters for optimal security. It cannot match your previous 5 passwords or contain common words." },
        { title: "Change Your Password", desc: "Navigate to Settings > Security > Change Password. Enter your current password, then create and confirm your new password. All active sessions will be logged out for security." },
        { title: "Password Expiration", desc: "For business accounts, administrators can set password expiration policies (e.g., require changes every 90 days). Individual users can change passwords anytime from their security settings." },
        { title: "Forgot Your Password?", desc: "Click 'Forgot Password' on the login page. Enter your email and follow the reset link sent to your inbox. The link expires in 1 hour for security. Create a new password after verification." },
        { title: "Password Strength Indicator", desc: "Our registration form shows real-time password strength feedback. Aim for 'Strong' or 'Excellent' before submitting. Use our password generator for instant strong passwords." }
      ]
    },
    {
      id: "sessions",
      title: "Active Sessions & Devices",
      description: "Monitor and control your account access",
      icon: Clock,
      color: "purple",
      steps: [
        { title: "View Active Sessions", desc: "Go to Settings > Security > Active Sessions to see all devices currently logged into your account. Each session shows device type, location, last activity, and login time." },
        { title: "Terminate a Session", desc: "Found an unfamiliar device? Click the three-dot menu next to any session and select 'Sign Out'. This immediately logs out that device. Do this for any sessions you don't recognize." },
        { title: "Sign Out Everywhere", desc: "In case of suspected compromise, use 'Sign Out Everywhere' in Security Settings. This logs out all devices except the current one. You'll need to log in again on each device." },
        { title: "Session Timeout", desc: "Sessions automatically expire after 30 days of inactivity or 8 hours of continuous activity. For sensitive actions, enable 'Require re-authentication' in your security settings." },
        { title: "IP Address Monitoring", desc: "Each session shows the IP address. If you see unfamiliar IPs, your account may be compromised. Contact support immediately and change your password." },
        { title: "Device Recognition", desc: "We remember trusted devices for 30 days. Unrecognized devices will require extra verification. You can mark devices as 'Trusted' to skip additional checks." }
      ]
    },
    {
      id: "team",
      title: "Team Permissions & Roles",
      description: "Manage user access and permissions",
      icon: Users,
      color: "amber",
      steps: [
        { title: "User Roles Explained", desc: "SOLEASE offers three main roles: Client (submit tickets), Reviewer (manage tickets), and Manager (full access). Each role has specific permissions for security." },
        { title: "Manager Role", desc: "Managers can view all tickets, assign reviewers, access reports, manage team members, and configure system settings. They have complete dashboard access." },
        { title: "Reviewer Role", desc: "Reviewers can view assigned tickets, update ticket status, communicate with clients, and add internal notes. They cannot access user management or billing." },
        { title: "Client Role", desc: "Clients can submit tickets, view their own tickets, provide feedback, and update their profile. They have the most limited access for security." },
        { title: "Invite Team Members", desc: "Managers can invite users from Settings > Team > Invite Member. Enter their email and select a role. They'll receive an invitation email to join." },
        { title: "Revoke Access", desc: "To remove a user, go to Settings > Team > select the user > click 'Remove'. Their access is immediately revoked. All their tickets remain but are reassigned." }
      ]
    },
    {
      id: "email",
      title: "Email Security",
      description: "Secure your connected email account",
      icon: Mail,
      color: "primary",
      steps: [
        { title: "Primary Email Security", desc: "Your SOLEASE account is linked to your email. Ensure this email has strong security: unique password, 2FA enabled, and regular monitoring for suspicious activity." },
        { title: "Change Your Email", desc: "Go to Settings > Profile > Email Address. You'll need to verify the new email before it becomes active. All notifications will then be sent to the new address." },
        { title: "Email Notifications", desc: "Configure which notifications you receive: ticket updates, assignment changes, system alerts. Adjust these in Settings > Notifications > Email Preferences." },
        { title: "Spam & Phishing", desc: "SOLEASE emails come from noreply@solease.com. Never click suspicious links in emails. Always verify sender addresses and report phishing attempts to security@solease.com." },
        { title: "Email Verification", desc: "New accounts require email verification. If you didn't receive the email, check spam/junk folders. Use 'Resend Verification' or contact support if issues persist." }
      ]
    }
  ];

  const currentGuide = guides.find(g => g.id === activeSection) || guides[0];

  const scrollToSection = (sectionId) => {
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
    setActiveSection(sectionId);
  };

  return (
    <DashboardLayout>
      <div className="max-w-7xl mx-auto px-3 sm:px-4 lg:px-6">
        {/* Header with Back Button */}
        <div className="flex items-center gap-2 sm:gap-4 mb-4 sm:mb-6">
          <button
            onClick={() => navigate("/help-support")}
            className="flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-2 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg text-xs sm:text-sm font-medium text-gray-700 dark:text-gray-300 transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            <span className="hidden xs:inline">Back to Help</span>
            <span className="xs:hidden">Back</span>
          </button>
        </div>

        {/* Introduction */}
        <div className="border-0 rounded-xl sm:rounded-2xl overflow-hidden bg-gradient-to-br from-blue-50 via-white to-indigo-50 dark:from-slate-900 dark:via-gray-900 dark:to-slate-800 shadow-lg mb-6 sm:mb-8">
          <div className="p-4 sm:p-6 lg:p-8">
            <div className="flex items-start gap-3 sm:gap-4 mb-3 sm:mb-4">
              <div className="w-10 h-10 sm:w-12 sm:h-12 lg:w-14 lg:h-14 rounded-xl sm:rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-blue-500/25 flex-shrink-0">
                <Shield className="w-5 h-5 sm:w-6 sm:h-6 lg:w-7 lg:h-7 text-white" />
              </div>
              <div className="min-w-0">
                <h3 className="text-base sm:text-lg lg:text-xl font-bold text-gray-900 dark:text-white">Account & Security</h3>
                <p className="text-xs sm:text-sm text-gray-500 dark:text-gray-400 font-medium">Complete guide to securing your SOLEASE account</p>
              </div>
            </div>
            <p className="text-sm sm:text-base text-gray-600 dark:text-gray-300 leading-relaxed mb-3 sm:mb-4">
              Learn how to protect your account with two-factor authentication, manage passwords, monitor active sessions, and control team access. 
              Follow these best practices to keep your SOLEASE account and data secure.
            </p>
            <div className="flex flex-wrap gap-2">
              <span className="px-2.5 sm:px-3 py-1 bg-blue-500/10 text-blue-600 dark:text-blue-400 text-xs sm:text-sm font-semibold rounded-full">2FA</span>
              <span className="px-2.5 sm:px-3 py-1 bg-green-500/10 text-green-600 dark:text-green-400 text-xs sm:text-sm font-semibold rounded-full">Passwords</span>
              <span className="px-2.5 sm:px-3 py-1 bg-purple-500/10 text-purple-600 dark:text-purple-400 text-xs sm:text-sm font-semibold rounded-full">Sessions</span>
              <span className="px-2.5 sm:px-3 py-1 bg-amber-500/10 text-amber-600 dark:text-amber-400 text-xs sm:text-sm font-semibold rounded-full">Team Access</span>
              <span className="px-2.5 sm:px-3 py-1 bg-primary/10 text-primary text-xs sm:text-sm font-semibold rounded-full">Email Security</span>
            </div>
          </div>
        </div>

        {/* Section Navigation */}
        <div className="flex flex-nowrap sm:flex-wrap gap-2 mb-6 sm:mb-8 overflow-x-auto pb-2 -mx-3 px-3 sm:mx-0 sm:px-0">
          {guides.map((guide, index) => (
            <button
              key={guide.id}
              onClick={() => scrollToSection(guide.id)}
              className={`flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-2 rounded-lg sm:rounded-xl text-xs sm:text-sm font-medium transition-all whitespace-nowrap flex-shrink-0 ${
                activeSection === guide.id
                  ? guide.color === "blue" ? "bg-blue-500 text-white shadow-lg shadow-blue-500/25" :
                    guide.color === "green" ? "bg-green-500 text-white shadow-lg shadow-green-500/25" :
                    guide.color === "purple" ? "bg-purple-500 text-white shadow-lg shadow-purple-500/25" :
                    guide.color === "amber" ? "bg-amber-500 text-white shadow-lg shadow-amber-500/25" :
                    "bg-primary text-white shadow-lg shadow-primary/25"
                  : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700"
              }`}
            >
              <guide.icon className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
              <span className="hidden md:inline">{guide.title.split('(')[0].trim()}</span>
              <span className="md:hidden">{index + 1}</span>
            </button>
          ))}
        </div>

        {/* Guide Sections */}
        <div className="space-y-6 sm:space-y-8">
          {guides.map((guide, guideIndex) => (
            <div 
              id={guide.id}
              key={guide.id}
              className="border-0 rounded-xl sm:rounded-2xl overflow-hidden bg-white dark:bg-gray-800 shadow-lg shadow-gray-100/50 dark:shadow-gray-900/50"
            >
              <div className="p-4 sm:p-5 lg:p-6 border-b border-gray-100 dark:border-gray-700 bg-gradient-to-r from-gray-50/50 to-white dark:from-gray-800 dark:to-gray-800">
                <div className="flex items-start gap-3 sm:gap-4">
                  <div className={`w-10 h-10 sm:w-11 sm:h-11 lg:w-12 lg:h-12 rounded-xl flex items-center justify-center shadow-md flex-shrink-0 ${
                    guide.color === "blue" ? "bg-gradient-to-br from-blue-500 to-blue-600 text-white shadow-blue-500/25" :
                    guide.color === "green" ? "bg-gradient-to-br from-green-500 to-green-600 text-white shadow-green-500/25" :
                    guide.color === "purple" ? "bg-gradient-to-br from-purple-500 to-purple-600 text-white shadow-purple-500/25" :
                    guide.color === "amber" ? "bg-gradient-to-br from-amber-500 to-amber-600 text-white shadow-amber-500/25" :
                    "bg-gradient-to-br from-primary to-primary/80 text-white shadow-primary/25"
                  }`}>
                    <guide.icon className="w-5 h-5 sm:w-5.5 sm:h-5.5 lg:w-6 lg:h-6" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-[10px] sm:text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider">Section {guideIndex + 1}</span>
                    </div>
                    <h4 className="text-base sm:text-lg font-bold text-gray-900 dark:text-white truncate">{guide.title}</h4>
                    <p className="text-xs sm:text-sm text-gray-500 dark:text-gray-400 line-clamp-1 sm:line-clamp-2">{guide.description}</p>
                  </div>
                </div>
              </div>
              <div className="p-4 sm:p-5 lg:p-6 bg-white dark:bg-gray-800">
                <div className="space-y-4 sm:space-y-6">
                  {guide.steps.map((step, index) => (
                    <div key={index} className="flex gap-3 sm:gap-4">
                      <div className="flex flex-col items-center flex-shrink-0">
                        <div className={`w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center text-xs sm:text-sm font-bold ${
                          index === 0 
                            ? guide.color === "blue" ? "bg-blue-500 text-white" :
                              guide.color === "green" ? "bg-green-500 text-white" :
                              guide.color === "purple" ? "bg-purple-500 text-white" :
                              guide.color === "amber" ? "bg-amber-500 text-white" :
                              "bg-primary text-white"
                            : "bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400"
                        }`}>
                          {index + 1}
                        </div>
                        {index < guide.steps.length - 1 && (
                          <div className="w-0.5 flex-1 bg-gradient-to-b from-gray-200 to-gray-100 dark:from-gray-700 dark:to-gray-800 mt-1.5 sm:mt-2" style={{ minHeight: '16px' }} />
                        )}
                      </div>
                      <div className="flex-1 min-w-0 pb-3 sm:pb-4">
                        <h5 className="text-sm sm:text-base font-semibold text-gray-900 dark:text-white mb-1">{step.title}</h5>
                        <p className="text-xs sm:text-sm text-gray-600 dark:text-gray-400 leading-relaxed">{step.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Security Checklist */}
        <div className="border-0 rounded-xl sm:rounded-2xl overflow-hidden bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 shadow-lg mt-6 sm:mt-8">
          <div className="p-4 sm:p-5 lg:p-6">
            <div className="flex items-center gap-2.5 sm:gap-3 mb-3 sm:mb-4">
              <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-lg bg-green-100 dark:bg-green-900/40 flex items-center justify-center flex-shrink-0">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-600 dark:text-green-400" />
              </div>
              <h4 className="text-base sm:text-lg font-bold text-gray-900 dark:text-white">Security Checklist</h4>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 sm:gap-3">
              <div className="flex items-start gap-2 p-2.5 sm:p-3 bg-white dark:bg-gray-800 rounded-lg">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Enable two-factor authentication</span>
              </div>
              <div className="flex items-start gap-2 p-2.5 sm:p-3 bg-white dark:bg-gray-800 rounded-lg">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Use a strong, unique password</span>
              </div>
              <div className="flex items-start gap-2 p-2.5 sm:p-3 bg-white dark:bg-gray-800 rounded-lg">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Review active sessions regularly</span>
              </div>
              <div className="flex items-start gap-2 p-2.5 sm:p-3 bg-white dark:bg-gray-800 rounded-lg">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Secure your connected email</span>
              </div>
              <div className="flex items-start gap-2 p-2.5 sm:p-3 bg-white dark:bg-gray-800 rounded-lg">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Store backup codes securely</span>
              </div>
              <div className="flex items-start gap-2 p-2.5 sm:p-3 bg-white dark:bg-gray-800 rounded-lg">
                <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-300">Log out on shared devices</span>
              </div>
            </div>
          </div>
        </div>

        {/* Need Help CTA */}
        <div className="border-0 rounded-xl sm:rounded-2xl overflow-hidden bg-gray-900 dark:bg-gray-800 shadow-xl mt-6 sm:mt-8 mb-6 sm:mb-8">
          <div className="p-5 sm:p-6 lg:p-8 text-center">
            <h4 className="text-lg sm:text-xl font-bold text-white mb-2">Security Concerns?</h4>
            <p className="text-gray-300 text-sm sm:text-base mb-4 sm:mb-6 max-w-lg mx-auto">
              If you suspect unauthorized access or have security questions, our team is here to help.
            </p>
            <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 justify-center">
              <button 
                onClick={() => navigate("/client-dashboard/new-ticket")}
                className="px-5 sm:px-6 py-2.5 sm:py-3 bg-primary hover:bg-primary/90 text-white font-semibold rounded-xl transition-colors flex items-center justify-center gap-2 text-sm"
              >
                <Ticket className="w-4 h-4 sm:w-5 sm:h-5" />
                Submit a Ticket
              </button>
              <button className="px-5 sm:px-6 py-2.5 sm:py-3 bg-gray-700 hover:bg-gray-600 text-white font-semibold rounded-xl transition-colors flex items-center justify-center gap-2 text-sm">
                <Headphones className="w-4 h-4 sm:w-5 sm:h-5" />
                Contact Support
              </button>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default AccountSecurityPage;